apiVersion: apps/v1
kind: Deployment

metadata:
  name: react-app
  namespace: react-devops

spec:
  replicas: 2

  selector:
    matchLabels:
      app: react-app

  strategy:
    type: RollingUpdate

  template:

    metadata:
      labels:
        app: react-app

    spec:

      containers:

      - name: react-app

        image: 345843270195.dkr.ecr.ap-southeast-2.amazonaws.com/react-devops-app:11

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        envFrom:
        - configMapRef:
            name: react-config

        - secretRef:
            name: react-secret

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "256Mi"

        volumeMounts:
        - name: storage
          mountPath: /usr/share/nginx/html/data

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 15

      volumes:

      - name: storage

        persistentVolumeClaim:
          claimName: react-pvc