apiVersion: v1
kind: PersistentVolume

metadata:
  name: react-pv

spec:
  capacity:
    storage: 1Gi

  volumeMode: Filesystem

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: gp3-storage

  claimRef:
    namespace: react-devops
    name: react-pvc

  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-00a8fe23843cfb505
    fsType: ext4