apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: react-pvc
  namespace: react-devops

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: gp3-storage

  resources:
    requests:
      storage: 1Gi